### ISSUE TITLE
Feedback and Suggestions

### ISSUE THREAD

**Issue by esibruti** [michalleptuch/fluent-emoji-gallery#2]
First of all, Michał, congratulations on another application that will give a lot of use to several people. The emojis, in fact, to add to works and things like that, it is very nice to have an application like this. As for the design, nothing to say, it follows the lines of Windows 11 and is flawless.

One suggestion I would give is translations. I think it is something that is already in your plans but if the translation is necessary, just call and deal with the Portuguese of Portugal.

Another feature (nothing urgent of course, just ideas) would be to make an emoji mixer, something similar and improved from this one: (https://fluent-emoji.ddiu.io/). That would be super interesting.

Oh and that part that is preparing things for the first time, it was very funny and very beautiful.

And that's it, on my part, I tested and really liked the usability of the application. 5⭐

**Comment by michalleptuch** [comment]
Hi, thank you for your feedback. I'm glad you like my app ☺️

At this moment I don't plan to translate this app. The names of emoji are copied from official Microsoft's repo of Fluent Emoji and I don't think there is anyone who wants to translate about 1500 names.

Emoji mixer is a good idea but it's based on SVG parts of emoji. In my app, I don't use `SvgImageSource` to display emoji because it has some issues with displaying curves and shades. Instead, I use `WebView2` to correctly display emoji. In this case, I don't see any possibilities to create emoji mixer using only `WebView2`.
